{
 "title": "Flask API Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total API requests per second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(request_count_total{endpoint=~\"/api/.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average API Latency (/api/)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((rate(request_latency_seconds_sum{endpoint=~\"/api/.*\"}[1m]) / ignoring(endpoint) rate(request_latency_seconds_count{endpoint=~\"/api/.*\"}[1m])) and rate(request_latency_seconds_count{endpoint=~\"/api/.*\"}[1m]) > 0)"
    }
   ]
  },
  {
   "title": "Total Requests (/api/devices)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_count_total{endpoint=\"/api/devices\"}"
    }
   ]
  },
  {
   "title": "Request Latency Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket[1m])) by (le))"
    }
   ]
  }
 ]
}