apiVersion: 1

datasources:
  - name: Prometheus_Cluster
    type: prometheus
    access: proxy
    url: http://prometheus-svc.smart-home.svc.cluster.local:9090
    isDefault: true
    editable: true

  - name: Prometheus_Local
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
